version: '3'

services:
  client:
      image: node:laters
      container_name: client
      build: ./client
      restart: always
      volumes:
        - ./client:/src/app/
      ports:
        - '3000:3000'
      environment:
        REACT_APP_HOST_PORT_SERVER: http://localhost:5000/
      network_mode: host
  server:
    image: node:laters
    container_name: server
    build: ./server
    restart: always
    ports:
    - '5000:5000'
    environment:
      DB_USER: postgres
      DB_HOST: localhost
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_DATABASE: appChat
      HOST: localhost
      PORT: 5000
    volumes:
    - ./server:/src/app/
    depends_on:
      - db
    network_mode: host

  db:
      image: postgres
      restart: always
      container_name: postgres
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=appChat
        - PGDATA=/var/lib/postgresql/data
      volumes:
        - ./pg:/var/lib/postgresql/dat
      ports:
        - '5432:5432'
      network_mode: host