import type { Metadata } from "next";
import React from "react";
import { Room } from "@/app/chat/_components/Room";
import { Navigation } from "@/app/chat/_components/Navigation";

export const metadata: Metadata = {
  title: "Your Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={
        "container mx-auto flex w-full h-full justify-center items-center"
      }
    >
      <div
        className={"w-[90%] h-[90%] bg-dark-black rounded-2xl shadow-md flex"}
      >
        <div
          className={
            "xl:min-w-[350px] md:min-w-[250px] md:block hidden flex-initial"
          }
        >
          <Navigation />
          <div className={"px-4"}>{children}</div>
        </div>
        <Room />
      </div>
    </div>
  );
}
